name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Release-cli:
    strategy:
      matrix:
        include:
          - os: [windows-latest, self-hosted, x64]
          - os: [macos-latest, self-hosted, x64]
          - os: [ubuntu-latest, self-hosted, x64]
          - os: [ubuntu-latest, self-hosted, ARM64]
          - os: [ubuntu-latest, self-hosted, ARM32]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Build
        run: |
          bash scripts.sh build server
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cmd/kfs-server/kfs-server-${{ matrix.os }}-${{ matrix.arch }}

  Release-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          bash scripts.sh build electron
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ui/dist/*.zip
            ui/dist/*.dmg
            ui/dist/*.exe
            ui/dist/*.snap
            ui/dist/*.AppImage
