name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Release-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
          - os: windows
            arch: amd64
          - os: linux
            arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          bash scripts.sh build server
          bash scripts.sh build cli
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cmd/kfs-cli/kfs-cli-${{ matrix.os }}-${{ matrix.arch }}
            cmd/kfs-server/kfs-server-${{ matrix.os }}-${{ matrix.arch }}

  Release-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          bash scripts.sh build electron
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ui/dist/*.zip
            ui/dist/*.dmg
            ui/dist/*.exe
            ui/dist/*.snap
            ui/dist/*.AppImage
