name: UnitTest

on:
  push:
  pull_request:

jobs:

  UnitTest_storage-local:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd storage/local && go test -v ./...

  UnitTest_sqlite-noncgo:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd sqlite/noncgo && go test -v ./...

  UnitTest_core:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd core && go test -v ./...

  UnitTest_kfs-cli:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Build
        run: bash scripts.sh build cli

      - name: Test
        run: |
          cd cmd/kfs-cli && go test -v ./...
