name: UnitTest

on:
  push:
  pull_request:

jobs:

  UnitTest-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: install mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'kfs'
          mysql root password: '12345678'
      - name: Build
        run: |
          bash scripts.sh unittest go

  UnitTest-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Test
        run: |
          bash scripts.sh unittest js
